server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/ajaykumar/Downloads/Java%20Spring/Java%20Spring%20Boot/E-commerce/config-repo
